#!/bin/bash

set -o errexit
set -o nounset

echo "Waiting for RabbitMQ server to start..."
sleep 10

echo "Starting Celery workers..."

celery -A core.celery.app:celery_app worker --loglevel=INFO

echo "All workers are starting..."
wait
echo "All workers have been started."
