"""Initial migration

Revision ID: 57ffde3babd2
Revises:
Create Date: 2025-09-09 09:28:23.557697

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "57ffde3babd2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "confirm_code",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("try_count", sa.Integer(), nullable=False),
        sa.Column("resend_count", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("expire_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unlock_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resend_unlock_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Creation timestamp of the table",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Last update timestamp of the table",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_confirm_code")),
    )
    op.create_index(
        op.f("ix_confirm_code_code"), "confirm_code", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_confirm_code_email"), "confirm_code", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_confirm_code_expire_time"),
        "confirm_code",
        ["expire_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_confirm_code_resend_count"),
        "confirm_code",
        ["resend_count"],
        unique=False,
    )
    op.create_index(
        op.f("ix_confirm_code_resend_unlock_time"),
        "confirm_code",
        ["resend_unlock_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_confirm_code_try_count"), "confirm_code", ["try_count"], unique=False
    )
    op.create_index(
        op.f("ix_confirm_code_unlock_time"),
        "confirm_code",
        ["unlock_time"],
        unique=False,
    )
    op.create_table(
        "custom_user",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "USER", name="userrole", native_enum=False),
            nullable=False,
        ),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Creation timestamp of the table",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Last update timestamp of the table",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custom_user")),
    )
    op.create_index(op.f("ix_custom_user_email"), "custom_user", ["email"], unique=True)
    op.create_index(op.f("ix_custom_user_role"), "custom_user", ["role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_custom_user_role"), table_name="custom_user")
    op.drop_index(op.f("ix_custom_user_email"), table_name="custom_user")
    op.drop_table("custom_user")
    op.drop_index(op.f("ix_confirm_code_unlock_time"), table_name="confirm_code")
    op.drop_index(op.f("ix_confirm_code_try_count"), table_name="confirm_code")
    op.drop_index(op.f("ix_confirm_code_resend_unlock_time"), table_name="confirm_code")
    op.drop_index(op.f("ix_confirm_code_resend_count"), table_name="confirm_code")
    op.drop_index(op.f("ix_confirm_code_expire_time"), table_name="confirm_code")
    op.drop_index(op.f("ix_confirm_code_email"), table_name="confirm_code")
    op.drop_index(op.f("ix_confirm_code_code"), table_name="confirm_code")
    op.drop_table("confirm_code")
    # ### end Alembic commands ###
